export const CLIENTE_REPOSITORY = 'CLIENTE_REPOSITORY';
export const ARTICULO_REPOSITORY = 'ARTICULO_REPOSITORY';
export const RESERVA_REPOSITORY = 'RESERVA_REPOSITORY';
export const ADMIN_REPOSITORY = 'ADMIN_REPOSITORY';